# 20200492.py — CS470 A3 Pacman Capture-the-Flag submission
#
# Flattened from zoo_reflex_tuned.py + zoo_core.py + zoo_features.py + A1 evolved weights.
# A1 provenance: CEM Phase 2a/2b, best-ever fitness 1.0652 (pm19). HTH vs
# baseline.py 158/200 = 79.0%, Wilson 95% CI [0.728, 0.841]. See
# experiments/artifacts/phase2_A1_17dim/ for genomes + HTH CSVs.
#
# Generated by experiments/flatten.py. Do not hand-edit.

from __future__ import annotations

import json
import math
import random
import time
from collections import deque

from captureAgents import CaptureAgent
from game import Directions
from util import TimeoutFunctionException, nearestPoint

# ===== zoo_features.py (20-dim feature extractor) =====
# zoo_features.py
# ---------------
# Shared feature extractor module for zoo reflex-family agents.
# Implements the 20-feature set from STRATEGY.md §4.1.
#
# All feature computations are wrapped in try/except returning 0.0 on failure.
# Final values are clipped to [-1e6, 1e6]. No inf/NaN emitted.
#
# Usage:
#   from zoo_features import extract_features, evaluate, SEED_WEIGHTS_OFFENSIVE, SEED_WEIGHTS_DEFENSIVE



# ---------------------------------------------------------------------------
# Seed weight dictionaries (gen-0 of CEM evolution)
# ---------------------------------------------------------------------------



# Preferred action order for deterministic tiebreak.
_ACTION_PREFERENCE = [
    Directions.NORTH,
    Directions.EAST,
    Directions.SOUTH,
    Directions.WEST,
    Directions.STOP,
]

_CLIP = 1e6


def _clip(v):
    """Clip a float to [-1e6, 1e6] and guard against inf/NaN."""
    try:
        if math.isnan(v) or math.isinf(v):
            return 0.0
        return max(-_CLIP, min(_CLIP, float(v)))
    except Exception:
        return 0.0


def extract_features(agent, gameState, action):
    """Compute the 20-feature dict for (agent, gameState, action).

    Uses agent.snapshot(), agent.getMazeDistance(), agent.bottlenecks,
    agent.deadEnds, agent.homeFrontier, and agent.red.

    All individual features are wrapped in try/except returning 0.0.
    Final dict values are clipped to [-1e6, 1e6] with no inf/NaN.

    Returns dict[str, float].
    """
    features = {
        'f_bias': 1.0,
        'f_successorScore': 0.0,
        'f_distToFood': 0.0,
        'f_distToCapsule': 0.0,
        'f_numCarrying': 0.0,
        'f_distToHome': 0.0,
        'f_ghostDist1': 0.0,
        'f_ghostDist2': 0.0,
        'f_inDeadEnd': 0.0,
        'f_stop': 0.0,
        'f_reverse': 0.0,
        'f_numInvaders': 0.0,
        'f_invaderDist': 0.0,
        'f_onDefense': 0.0,
        'f_patrolDist': 0.0,
        'f_distToCapsuleDefend': 0.0,
        'f_scaredFlee': 0.0,
        # B1 (pm18): zero-defaults; computed below before the clip pass.
        'f_scaredGhostChase': 0.0,
        'f_returnUrgency': 0.0,
        'f_teammateSpread': 0.0,
    }

    # --- Compute successor state ---
    try:
        successor = gameState.generateSuccessor(agent.index, action)
        # If only half a grid step was covered, advance one more step.
        from util import nearestPoint
        pos_raw = successor.getAgentState(agent.index).getPosition()
        if pos_raw != nearestPoint(pos_raw):
            successor = successor.generateSuccessor(agent.index, action)
    except Exception:
        successor = gameState  # fallback: evaluate current state

    # --- Snapshot of successor ---
    try:
        snap = agent.snapshot(successor)
    except Exception:
        snap = {
            'myPos': None, 'myState': None, 'isPacman': False,
            'scaredTimer': 0, 'numCarrying': 0, 'foodList': [],
            'defendFoodList': [], 'capsuleList': [], 'opponentPositions': {},
            'teamPositions': {}, 'walls': None,
        }

    myPos = snap.get('myPos')
    myState = snap.get('myState')
    isPacman = snap.get('isPacman', False)
    scaredTimer = snap.get('scaredTimer', 0)
    numCarrying = snap.get('numCarrying', 0)
    foodList = snap.get('foodList', [])
    capsuleList = snap.get('capsuleList', [])
    opponentPositions = snap.get('opponentPositions', {})

    # -----------------------------------------------------------------------
    # f_bias
    # -----------------------------------------------------------------------
    features['f_bias'] = 1.0

    # -----------------------------------------------------------------------
    # f_successorScore = -len(remaining food to eat)
    # -----------------------------------------------------------------------
    try:
        features['f_successorScore'] = float(-len(foodList))
    except Exception:
        features['f_successorScore'] = 0.0

    # -----------------------------------------------------------------------
    # f_distToFood = 1 / max(min_dist_to_remaining_food, 1); 0 if no food
    # -----------------------------------------------------------------------
    try:
        if myPos is not None and foodList:
            min_food_dist = min(agent.getMazeDistance(myPos, f) for f in foodList)
            features['f_distToFood'] = 1.0 / max(min_food_dist, 1)
        else:
            features['f_distToFood'] = 0.0
    except Exception:
        features['f_distToFood'] = 0.0

    # -----------------------------------------------------------------------
    # f_distToCapsule = 1 / max(min_dist_to_capsule, 1); 0 if no capsule
    # -----------------------------------------------------------------------
    try:
        if myPos is not None and capsuleList:
            min_cap_dist = min(agent.getMazeDistance(myPos, c) for c in capsuleList)
            features['f_distToCapsule'] = 1.0 / max(min_cap_dist, 1)
        else:
            features['f_distToCapsule'] = 0.0
    except Exception:
        features['f_distToCapsule'] = 0.0

    # -----------------------------------------------------------------------
    # f_numCarrying
    # -----------------------------------------------------------------------
    try:
        features['f_numCarrying'] = float(numCarrying)
    except Exception:
        features['f_numCarrying'] = 0.0

    # -----------------------------------------------------------------------
    # f_distToHome = 1/max(dist_to_nearest_home_frontier, 1) * numCarrying
    # Only meaningful when carrying; 0 if not carrying or no frontier.
    # -----------------------------------------------------------------------
    try:
        homeFrontier = agent.homeFrontier if agent.homeFrontier else []
        if myPos is not None and numCarrying > 0 and homeFrontier:
            min_home_dist = min(agent.getMazeDistance(myPos, h) for h in homeFrontier)
            features['f_distToHome'] = (1.0 / max(min_home_dist, 1)) * numCarrying
        else:
            features['f_distToHome'] = 0.0
    except Exception:
        features['f_distToHome'] = 0.0

    # -----------------------------------------------------------------------
    # Ghost distances: find active (non-scared) enemy ghosts visible to us.
    # f_ghostDist1 = -1/max(nearest_active_ghost_dist, 1); 0 if none
    # f_ghostDist2 = -1/max(second_nearest, 1); 0 if fewer than 2
    # -----------------------------------------------------------------------
    try:
        active_ghost_dists = []
        if myPos is not None:
            for opp_idx, opp_pos in opponentPositions.items():
                if opp_pos is None:
                    continue
                try:
                    opp_state = successor.getAgentState(opp_idx)
                    opp_is_pacman = getattr(opp_state, 'isPacman', False)
                    opp_scared = int(getattr(opp_state, 'scaredTimer', 0) or 0)
                    if opp_is_pacman:
                        continue  # they are Pacman, not a ghost threat
                    if opp_scared > 0:
                        continue  # scared ghost is not a threat
                    dist = agent.getMazeDistance(myPos, opp_pos)
                    active_ghost_dists.append(dist)
                except Exception:
                    continue
        active_ghost_dists.sort()
        if len(active_ghost_dists) >= 1:
            features['f_ghostDist1'] = -1.0 / max(active_ghost_dists[0], 1)
        else:
            features['f_ghostDist1'] = 0.0
        if len(active_ghost_dists) >= 2:
            features['f_ghostDist2'] = -1.0 / max(active_ghost_dists[1], 1)
        else:
            features['f_ghostDist2'] = 0.0
    except Exception:
        features['f_ghostDist1'] = 0.0
        features['f_ghostDist2'] = 0.0

    # -----------------------------------------------------------------------
    # f_inDeadEnd: 1.0 if successor position is in a dead-end cell AND
    # an active enemy ghost is within distance 4; else 0.
    # -----------------------------------------------------------------------
    try:
        deadEnds = agent.deadEnds if agent.deadEnds else frozenset()
        in_dead = (myPos in deadEnds) if myPos is not None else False
        if in_dead and active_ghost_dists and active_ghost_dists[0] <= 4:
            features['f_inDeadEnd'] = 1.0
        else:
            features['f_inDeadEnd'] = 0.0
    except Exception:
        features['f_inDeadEnd'] = 0.0

    # -----------------------------------------------------------------------
    # f_stop: 1.0 if action == STOP
    # -----------------------------------------------------------------------
    try:
        features['f_stop'] = 1.0 if action == Directions.STOP else 0.0
    except Exception:
        features['f_stop'] = 0.0

    # -----------------------------------------------------------------------
    # f_reverse: 1.0 if action reverses current direction
    # -----------------------------------------------------------------------
    try:
        cur_dir = gameState.getAgentState(agent.index).configuration.direction
        rev_dir = Directions.REVERSE[cur_dir]
        features['f_reverse'] = 1.0 if action == rev_dir else 0.0
    except Exception:
        features['f_reverse'] = 0.0

    # -----------------------------------------------------------------------
    # Defensive features
    # -----------------------------------------------------------------------

    # f_numInvaders: count of opponent Pacmen on our side
    # f_invaderDist: 1 / max(min_invader_dist, 1) — defender chases
    # -----------------------------------------------------------------------
    try:
        invader_dists = []
        for opp_idx, opp_pos in opponentPositions.items():
            if opp_pos is None:
                continue
            try:
                opp_state = successor.getAgentState(opp_idx)
                if getattr(opp_state, 'isPacman', False):
                    if myPos is not None:
                        d = agent.getMazeDistance(myPos, opp_pos)
                        invader_dists.append(d)
            except Exception:
                continue
        features['f_numInvaders'] = float(len(invader_dists))
        if invader_dists:
            features['f_invaderDist'] = 1.0 / max(min(invader_dists), 1)
        else:
            features['f_invaderDist'] = 0.0
    except Exception:
        features['f_numInvaders'] = 0.0
        features['f_invaderDist'] = 0.0

    # -----------------------------------------------------------------------
    # f_onDefense: 1.0 if successor agent is NOT Pacman (i.e. on home side)
    # -----------------------------------------------------------------------
    try:
        features['f_onDefense'] = 0.0 if isPacman else 1.0
    except Exception:
        features['f_onDefense'] = 0.0

    # -----------------------------------------------------------------------
    # f_patrolDist: 1/max(dist_to_rotating_patrol_anchor, 1)
    # Anchor = closest bottleneck cell from homeFrontier (or nearest
    # homeFrontier cell if no bottlenecks overlap).
    # -----------------------------------------------------------------------
    try:
        homeFrontier = agent.homeFrontier if agent.homeFrontier else []
        bottlenecks = agent.bottlenecks if agent.bottlenecks else frozenset()

        anchor = None
        if myPos is not None and homeFrontier:
            # Prefer bottleneck cells on the home frontier as patrol anchors.
            frontier_bottlenecks = [c for c in homeFrontier if c in bottlenecks]
            if frontier_bottlenecks:
                # Rotating anchor: pick the one closest to myPos.
                anchor = min(frontier_bottlenecks, key=lambda c: agent.getMazeDistance(myPos, c))
            else:
                # Fall back to nearest frontier cell.
                anchor = min(homeFrontier, key=lambda c: agent.getMazeDistance(myPos, c))

        if anchor is not None and myPos is not None:
            d = agent.getMazeDistance(myPos, anchor)
            features['f_patrolDist'] = 1.0 / max(d, 1)
        else:
            features['f_patrolDist'] = 0.0
    except Exception:
        features['f_patrolDist'] = 0.0

    # -----------------------------------------------------------------------
    # f_distToCapsuleDefend: -1/max(dist_to_our_defending_capsule, 1)
    # "Our defending capsule" = capsule on our side (getCapsulesYouAreDefending).
    # Defender wants enemies AWAY from our capsule (hence negative: the closer
    # the defender is to the capsule, the higher the negative penalty → the
    # weight must be negative to make being close desirable).
    # Actually the feature is negative when close — agent should apply a
    # negative weight to push away, OR be close to intercept.
    # Per plan: f_distToCapsuleDefend = -1/max(dist, 1) so with weight -3,
    # value is +3/dist → agent is rewarded for being close to our capsule.
    # -----------------------------------------------------------------------
    try:
        if myPos is not None:
            defend_caps = list(agent.getCapsulesYouAreDefending(successor))
            if defend_caps:
                min_dcap_dist = min(agent.getMazeDistance(myPos, c) for c in defend_caps)
                features['f_distToCapsuleDefend'] = -1.0 / max(min_dcap_dist, 1)
            else:
                features['f_distToCapsuleDefend'] = 0.0
        else:
            features['f_distToCapsuleDefend'] = 0.0
    except Exception:
        features['f_distToCapsuleDefend'] = 0.0

    # -----------------------------------------------------------------------
    # f_scaredFlee: if scaredTimer > 0, flip sign of f_invaderDist (flee).
    # When scared, defender should flee from invaders rather than chase.
    # -----------------------------------------------------------------------
    try:
        if scaredTimer > 0:
            # Positive f_invaderDist means agent is close to invader (= good when chasing).
            # Flip sign so that being close is bad (flee).
            features['f_scaredFlee'] = -features['f_invaderDist']
        else:
            features['f_scaredFlee'] = 0.0
    except Exception:
        features['f_scaredFlee'] = 0.0

    # -----------------------------------------------------------------------
    # f_scaredGhostChase (B1, pm18): 1/dist to nearest SCARED enemy ghost.
    # Positive value = closer to scared ghost. Evolved +weight → chase for
    # points & ghost-kill. Currently no other feature captures this bonus.
    # -----------------------------------------------------------------------
    try:
        scared_ghost_dists = []
        if myPos is not None:
            for opp_idx, opp_pos in opponentPositions.items():
                if opp_pos is None:
                    continue
                try:
                    opp_state = successor.getAgentState(opp_idx)
                    if getattr(opp_state, 'isPacman', False):
                        continue
                    opp_scared = int(getattr(opp_state, 'scaredTimer', 0) or 0)
                    if opp_scared <= 0:
                        continue
                    d = agent.getMazeDistance(myPos, opp_pos)
                    scared_ghost_dists.append(d)
                except Exception:
                    continue
        if scared_ghost_dists:
            features['f_scaredGhostChase'] = 1.0 / max(min(scared_ghost_dists), 1)
        else:
            features['f_scaredGhostChase'] = 0.0
    except Exception:
        features['f_scaredGhostChase'] = 0.0

    # -----------------------------------------------------------------------
    # f_returnUrgency (B1, pm18): non-linear return-home pressure.
    #   numCarrying² × (1/home_dist) × (0.5 + time_factor)
    # time_factor = 1 − timeleft/1200 grows 0→1 as the game advances; the
    # 0.5 floor keeps baseline return pressure present from move 0, and the
    # squared carrying term lets a large hoard dominate the expression even
    # at long home distances. Existing f_distToHome is linear in both;
    # this gives evolution an extra lever for late-game scoring rushes.
    # -----------------------------------------------------------------------
    try:
        try:
            time_left = int(gameState.data.timeleft)
        except Exception:
            time_left = 1200
        time_factor = 1.0 - (max(0, min(time_left, 1200)) / 1200.0)
        homeFrontier = agent.homeFrontier if agent.homeFrontier else []
        if myPos is not None and numCarrying > 0 and homeFrontier:
            min_home_dist = min(agent.getMazeDistance(myPos, h) for h in homeFrontier)
            features['f_returnUrgency'] = (
                (float(numCarrying) ** 2)
                * (1.0 / max(min_home_dist, 1))
                * (0.5 + time_factor)
            )
        else:
            features['f_returnUrgency'] = 0.0
    except Exception:
        features['f_returnUrgency'] = 0.0

    # -----------------------------------------------------------------------
    # f_teammateSpread (B1, pm18): 1/dist to the closest teammate. A
    # NEGATIVE weight → the agent disperses (being close is bad). Prevents
    # both offense agents from dogpiling the same food path. No existing
    # feature expresses teammate geometry.
    # -----------------------------------------------------------------------
    try:
        teammate_dists = []
        if myPos is not None:
            try:
                team_indices = list(agent.getTeam(successor))
            except Exception:
                team_indices = []
            for tm_idx in team_indices:
                if tm_idx == agent.index:
                    continue
                try:
                    tm_pos = successor.getAgentPosition(tm_idx)
                    if tm_pos is None:
                        continue
                    d = agent.getMazeDistance(myPos, tm_pos)
                    teammate_dists.append(d)
                except Exception:
                    continue
        if teammate_dists:
            features['f_teammateSpread'] = 1.0 / max(min(teammate_dists), 1)
        else:
            features['f_teammateSpread'] = 0.0
    except Exception:
        features['f_teammateSpread'] = 0.0

    # -----------------------------------------------------------------------
    # Final clip pass — ensure no inf/NaN in output.
    # -----------------------------------------------------------------------
    for k in features:
        features[k] = _clip(features[k])

    return features


def evaluate(agent, gameState, action, weights):
    """Compute weighted sum of features. Returns float.

    Returns -inf on any unexpected exception so argmax skips the broken action.
    """
    try:
        feats = extract_features(agent, gameState, action)
        return sum(weights.get(f, 0.0) * v for f, v in feats.items())
    except Exception:
        return float('-inf')

# ===== A1 evolved weights (Phase 2b best-ever fitness 1.0652) =====
SEED_WEIGHTS_OFFENSIVE = {
    'f_bias': -10.017253817246377,
    'f_distToCapsule': 48.360302883620825,
    'f_distToCapsuleDefend': 1.547679231272756,
    'f_distToFood': 34.14345004689613,
    'f_distToHome': 13.852974306227107,
    'f_ghostDist1': -28.64694661198477,
    'f_ghostDist2': -25.991088517730326,
    'f_inDeadEnd': -230.89111625051996,
    'f_invaderDist': 27.36130581569995,
    'f_numCarrying': -30.09700974100203,
    'f_numInvaders': -61.89167508020655,
    'f_onDefense': -7.79320320637998,
    'f_patrolDist': 11.407629912078363,
    'f_reverse': -29.435663611066094,
    'f_scaredFlee': 5.147411643023573,
    'f_stop': -143.24929989889085,
    'f_successorScore': 108.96829684046561,
}

SEED_WEIGHTS_DEFENSIVE = {
    'f_bias': 9.254227853334104,
    'f_distToCapsule': 36.52238855060967,
    'f_distToCapsuleDefend': -9.092917588436512,
    'f_distToFood': 31.764883169344376,
    'f_distToHome': 19.05708284807664,
    'f_ghostDist1': -30.70452674118357,
    'f_ghostDist2': -15.598619658875752,
    'f_inDeadEnd': -222.6171654915034,
    'f_invaderDist': 44.99699820378971,
    'f_numCarrying': -38.312336112809334,
    'f_numInvaders': -47.2277215189426,
    'f_onDefense': -12.119478810302255,
    'f_patrolDist': 6.945009803552975,
    'f_reverse': -37.51172016761111,
    'f_scaredFlee': 14.32142901323801,
    'f_stop': -137.1772952141375,
    'f_successorScore': 104.98884086224324,
}

# ===== zoo_core.py (CoreCaptureAgent, TEAM, weight-override loader) =====
# zoo_core.py
# -----------
# Shared base agent for the dev "zoo". Concretely the equivalent of the
# `experiments/zoo/_core.py` module described in STRATEGY.md, but located
# inside `minicontest/` so that capture.py's `-r {name}` import mechanism
# (which imports `{name}.py` from CWD) can discover both `zoo_core` itself
# and any concrete `zoo_<variant>.py` agent that inherits from it.
#
# Submission-time flattening (M9) inlines this file's classes/methods into
# the per-file `your_*.py` artifacts so the final submission satisfies the
# single-file constraint. During development, every zoo agent imports
# CoreCaptureAgent and TEAM from here.
#
# This module is NOT one of the "do-not-modify" framework files, but it
# does NOT modify any of them either.




# ---------------------------------------------------------------------------
# Module-level constants (PRE-CALIBRATION values)
# ---------------------------------------------------------------------------
# pre-calibration value; will be updated by M7.5 artifact. Algorithmic bounds
# (MAX_ITERS/MAX_DEPTH) are the primary time controller during M1-M7.
MOVE_BUDGET = 0.80

# pre-calibration value; will be updated by M7.5 artifact. Algorithmic bounds
# (MAX_ITERS/MAX_DEPTH) are the primary time controller during M1-M7.
MAX_ITERS = 1000
# pre-calibration value; will be updated by M7.5 artifact. Algorithmic bounds
# (MAX_ITERS/MAX_DEPTH) are the primary time controller during M1-M7.
MAX_DEPTH = 3
# pre-calibration value; will be updated by M7.5 artifact. Algorithmic bounds
# (MAX_ITERS/MAX_DEPTH) are the primary time controller during M1-M7.
ROLLOUT_DEPTH = 20

# Layout-size guard for bottleneck precomputation: skip if too many open cells.
_BOTTLENECK_MAX_CELLS = 500

# APSP timing thresholds (seconds). Soft warn only — never raise.
_APSP_WARN_SEC = 8.0


# ---------------------------------------------------------------------------
# TeamGlobalState — module-level singleton shared between teammates.
# Both teammates run inside the same process (CS188 framework, no IPC), and
# turns are sequential, so the same Python object is observable from both
# `chooseAction` calls without any synchronization.
# ---------------------------------------------------------------------------
class TeamGlobalState:
    """Mutable shared state for the two teammate agents.

    All mutations happen during sequential `chooseAction` calls — there is
    never concurrent access (CS188 framework owns the turn loop). All public
    methods MUST be exception-safe; callers cannot afford a crash in the
    coordination layer.
    """

    def __init__(self):
        self.initialized = False
        # agent_index -> "OFFENSE" | "DEFENSE"
        self.role = {}
        # agent_index -> (x, y, tick)
        self.last_seen_enemy = {}
        # list of (food_pos, tick) for food eaten by us
        self.food_eaten_by_us = []
        # capsule_pos -> tick when eaten
        self.capsule_eaten_tick = {}
        # agent_index -> int counter for hysteresis
        self.switch_counter = {}
        # global tick counter (incremented by either teammate)
        self.tick = 0

    def reset(self, gameState):
        """Idempotent reset — initialize role assignment exactly once per game.

        Default role assignment: lower-index agent → OFFENSE,
        higher-index agent → DEFENSE. Both teammates read the same dict
        so the two agents auto-agree without any messaging.
        """
        if self.initialized:
            return
        try:
            # Determine which side we are on by looking at the first agent
            # whose `red` field happens to be queryable. We do not depend on
            # `self` here — the singleton has no agent context — so we use
            # the gameState directly.
            red_indices = list(gameState.getRedTeamIndices())
            blue_indices = list(gameState.getBlueTeamIndices())
            for indices in (red_indices, blue_indices):
                if not indices:
                    continue
                sorted_idx = sorted(indices)
                # lower-index agents OFFENSE, higher DEFENSE
                for rank, idx in enumerate(sorted_idx):
                    self.role[idx] = "OFFENSE" if rank == 0 else "DEFENSE"
                    self.switch_counter[idx] = 0
                    self.last_seen_enemy[idx] = None
            self.tick = 0
            self.food_eaten_by_us = []
            self.capsule_eaten_tick = {}
            self.initialized = True
        except Exception:
            # Defensive — if anything goes wrong building defaults, at least
            # mark initialized so we do not keep retrying. Subclass code is
            # expected to fall back to its own role logic if `role` is empty.
            self.initialized = True

    def force_reinit(self):
        """Hard reset — wipe all state. Called from registerInitialState's
        fallback path when `reset()` itself raised."""
        self.__init__()


# Module-level singleton — shared across both teammate agents because they
# import the same `zoo_core` module.
TEAM = TeamGlobalState()


# ---------------------------------------------------------------------------
# Weight-override protocol (M4b-2, 2026-04-15 pm8)
# ---------------------------------------------------------------------------
# During CEM evolution (evolve.py M5/M6), each candidate genome encodes a
# fresh (w_off, w_def, params) set that must be injected into a zoo agent
# at runtime. We piggyback on capture.py's existing `--redOpts` / `--blueOpts`
# channel: the tournament passes `weights=<json_path>` as an agent arg; the
# agent's `createTeam(...)` forwards that to this loader, and the agent's
# `_get_weights()` returns the loaded dict instead of the seed weights.
#
# JSON schema:
#     { "w_off": {feature_name: weight, ...},
#       "w_def": {feature_name: weight, ...} | null,
#       "params": {param_name: value, ...} }
#
# Phase 2a of evolution uses a shared W (w_def == null → agents fall back to
# w_off for both OFFENSE and DEFENSE roles). Phase 2b splits W_OFF ≠ W_DEF
# and supplies both.
def load_weights_override(spec):
    """Load a weight override from a JSON-file path or from a pre-parsed dict.

    Returns a dict with the canonical keys `w_off`, `w_def`, `params`. Keys
    missing in the source are filled with a safe default (`{}` or `None`).
    Never raises: on ANY failure (bad path, malformed JSON, wrong type) we
    return an empty override so the agent cleanly falls back to seed weights.
    The 15s registerInitialState budget cannot afford a crash here.
    """
    import json
    empty = {"w_off": {}, "w_def": None, "params": {}}
    try:
        if isinstance(spec, dict):
            data = spec
        else:
            with open(spec) as f:
                data = json.load(f)
        if not isinstance(data, dict):
            return empty
        w_off_raw = data.get("w_off") or {}
        w_def_raw = data.get("w_def")
        params_raw = data.get("params") or {}
        return {
            "w_off": dict(w_off_raw) if isinstance(w_off_raw, dict) else {},
            "w_def": (dict(w_def_raw) if isinstance(w_def_raw, dict) else None),
            "params": dict(params_raw) if isinstance(params_raw, dict) else {},
        }
    except Exception:
        return empty


# ---------------------------------------------------------------------------
# CoreCaptureAgent — shared base for every zoo agent.
# ---------------------------------------------------------------------------
class CoreCaptureAgent(CaptureAgent):
    """Crash-proof base agent.

    Subclasses MUST override `_chooseActionImpl(gameState)`. Everything else
    (timing, state snapshot, distance lookups, fallback) is provided here.

    Hard guarantees:
      * `registerInitialState` never raises (every step independently
        guarded). A 15s init crash would forfeit the game.
      * `chooseAction` never raises EXCEPT for `TimeoutFunctionException`,
        which we deliberately re-raise so the framework's SIGALRM
        bookkeeping (warning counter, forfeit) stays correct.
      * `_safeFallback` never raises.
    """

    # ----- init -------------------------------------------------------------

    def __init__(self, index, timeForComputing=0.1):
        # Call CaptureAgent.__init__ (sets self.index, self.distancer=None,
        # observationHistory=[], etc.). Mirrors the baseline pattern.
        CaptureAgent.__init__(self, index, timeForComputing)

        # Per-agent state populated in registerInitialState. Each has a safe
        # default in case its precompute step raises.
        self.start = None
        self.apsp = None  # dict[(pos1, pos2)] -> int, or None → fallback to distancer
        self.bottlenecks = frozenset()
        self.deadEnds = frozenset()
        self.homeFrontier = []
        self.turn_start = 0.0

    # ----- registerInitialState (15s budget; crash-proof) -------------------

    def registerInitialState(self, gameState):
        """Heavy precompute, every step independently guarded.

        Steps (order matters for fallbacks):
          1. CaptureAgent.registerInitialState — populates self.distancer.
          2. self.start (agent spawn).
          3. APSP dict — O(1) maze-distance lookups.
          4. Bottlenecks (frozenset of articulation cells).
          5. Dead-ends (frozenset).
          6. Home-frontier (list of border cells on our side).
          7. TEAM singleton reset.
        """
        # 1) Base distancer + standard CaptureAgent setup.
        try:
            CaptureAgent.registerInitialState(self, gameState)
        except Exception:
            pass

        # 2) Spawn point.
        try:
            self.start = gameState.getAgentPosition(self.index)
        except Exception:
            self.start = None

        # 3) APSP — O(N^2) memory but worth it for O(1) per-move lookups.
        try:
            self.apsp = self._precomputeAPSP(gameState)
        except Exception:
            self.apsp = None

        # 4) Bottlenecks — articulation-point approximation (cheap BFS).
        try:
            self.bottlenecks = self._computeBottlenecks(gameState)
        except Exception:
            self.bottlenecks = frozenset()

        # 5) Dead-ends — single-exit cells with depth >= 3 from any junction.
        try:
            self.deadEnds = self._precomputeDeadEnds(gameState)
        except Exception:
            self.deadEnds = frozenset()

        # 6) Home-frontier — cells on our side adjacent to the divider.
        try:
            self.homeFrontier = self._computeHomeFrontier(gameState)
        except Exception:
            self.homeFrontier = []

        # 7) Team singleton — idempotent; safe to call from both teammates.
        try:
            TEAM.reset(gameState)
        except Exception:
            try:
                TEAM.force_reinit()
            except Exception:
                pass

        # NEVER raise from here.

    # ----- chooseAction (timeout-preserving two-layer wrap) ----------------

    def chooseAction(self, gameState):
        """Crash-proof entry point. Returns a legal action or STOP.

        TimeoutFunctionException is the framework's SIGALRM signal — we MUST
        re-raise it so the framework's warning counter and forfeit logic
        work correctly.
        """
        self.turn_start = time.time()
        try:
            action = self._chooseActionImpl(gameState)
            legal = gameState.getLegalActions(self.index)
            if action not in legal:
                action = self._safeFallback(gameState, legal)
            return action
        except TimeoutFunctionException:
            raise  # CRITICAL: let framework see it
        except Exception:
            try:
                legal = gameState.getLegalActions(self.index)
                fallback = self._safeFallback(gameState, legal)
                if fallback in legal:
                    return fallback
                non_stop = [a for a in legal if a != Directions.STOP]
                return random.choice(non_stop) if non_stop else Directions.STOP
            except TimeoutFunctionException:
                raise
            except Exception:
                return Directions.STOP

    def _chooseActionImpl(self, gameState):
        """Subclasses MUST override. Returns a legal action."""
        raise NotImplementedError(
            "CoreCaptureAgent subclasses must implement _chooseActionImpl"
        )

    def _safeFallback(self, gameState, legal):
        """Pick a non-STOP legal action, else STOP. NEVER raises."""
        try:
            if not legal:
                return Directions.STOP
            non_stop = [a for a in legal if a != Directions.STOP]
            if non_stop:
                return random.choice(non_stop)
            return Directions.STOP
        except Exception:
            return Directions.STOP

    # ----- helpers ----------------------------------------------------------

    def snapshot(self, gameState):
        """Compute a per-turn dict of common features. Computed once per
        chooseAction so search-evaluators can read a stable snapshot.

        All field accesses are guarded; missing data degrades to a sensible
        default rather than raising.
        """
        snap = {
            "myPos": None,
            "myState": None,
            "isPacman": False,
            "scaredTimer": 0,
            "numCarrying": 0,
            "foodList": [],
            "defendFoodList": [],
            "capsuleList": [],
            "opponentPositions": {},  # idx -> (x, y) or None
            "teamPositions": {},      # idx -> (x, y) or None
            "walls": None,
        }
        try:
            myState = gameState.getAgentState(self.index)
            snap["myState"] = myState
            try:
                pos = myState.getPosition()
                if pos is not None:
                    snap["myPos"] = (int(pos[0]), int(pos[1]))
            except Exception:
                snap["myPos"] = None
            snap["isPacman"] = bool(getattr(myState, "isPacman", False))
            snap["scaredTimer"] = int(getattr(myState, "scaredTimer", 0) or 0)
            snap["numCarrying"] = int(getattr(myState, "numCarrying", 0) or 0)
        except Exception:
            pass

        try:
            snap["foodList"] = self.getFood(gameState).asList()
        except Exception:
            snap["foodList"] = []

        try:
            snap["defendFoodList"] = self.getFoodYouAreDefending(gameState).asList()
        except Exception:
            snap["defendFoodList"] = []

        try:
            snap["capsuleList"] = list(self.getCapsules(gameState))
        except Exception:
            snap["capsuleList"] = []

        try:
            for idx in self.getOpponents(gameState):
                try:
                    snap["opponentPositions"][idx] = gameState.getAgentPosition(idx)
                except Exception:
                    snap["opponentPositions"][idx] = None
        except Exception:
            pass

        try:
            for idx in self.getTeam(gameState):
                try:
                    snap["teamPositions"][idx] = gameState.getAgentPosition(idx)
                except Exception:
                    snap["teamPositions"][idx] = None
        except Exception:
            pass

        try:
            snap["walls"] = gameState.getWalls()  # reference, not copy
        except Exception:
            snap["walls"] = None

        return snap

    def getMazeDistance(self, pos1, pos2):
        """O(1) APSP lookup if available, else fall back to base distancer."""
        try:
            if self.apsp is not None:
                d = self.apsp.get((pos1, pos2))
                if d is not None:
                    return d
        except Exception:
            pass
        try:
            return self.distancer.getDistance(pos1, pos2)
        except Exception:
            # Last-resort manhattan, mostly so callers do not crash on
            # unreachable / odd positions.
            try:
                return abs(pos1[0] - pos2[0]) + abs(pos1[1] - pos2[1])
            except Exception:
                return 0

    # ----- precompute -------------------------------------------------------

    def _precomputeAPSP(self, gameState):
        """All-Pairs Shortest Path via N independent BFS runs from every
        non-wall cell. Returns dict[(pos1, pos2)] -> int.

        Symmetric — we only BFS from each source once and rely on the
        unweighted-graph property `d(a,b) == d(b,a)`.
        """
        walls = gameState.getWalls()
        width, height = walls.width, walls.height

        # Open cells (non-wall).
        cells = []
        for x in range(width):
            for y in range(height):
                if not walls[x][y]:
                    cells.append((x, y))

        apsp = {}
        t0 = time.time()
        for src in cells:
            # BFS
            visited = {src: 0}
            queue = deque([src])
            while queue:
                cx, cy = queue.popleft()
                d = visited[(cx, cy)]
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    nx, ny = cx + dx, cy + dy
                    if nx < 0 or ny < 0 or nx >= width or ny >= height:
                        continue
                    if walls[nx][ny]:
                        continue
                    if (nx, ny) in visited:
                        continue
                    visited[(nx, ny)] = d + 1
                    queue.append((nx, ny))
            for dst, d in visited.items():
                apsp[(src, dst)] = d

        elapsed = time.time() - t0
        if elapsed > _APSP_WARN_SEC:
            # Soft warning only — never raise from precompute.
            try:
                print(
                    "[zoo_core] WARNING: APSP precompute took %.2fs "
                    "(>%.1fs threshold) on %dx%d layout (%d open cells)"
                    % (elapsed, _APSP_WARN_SEC, width, height, len(cells))
                )
            except Exception:
                pass
        return apsp

    def _computeBottlenecks(self, gameState):
        """Articulation-point approximation: a non-wall cell is a
        "bottleneck" if removing it disconnects its 4-neighbors.

        We only check cells with >= 2 non-wall neighbors. For each such
        cell, run BFS from one neighbor with the cell itself blocked, and
        verify all other non-wall neighbors are reachable.

        Skipped on layouts with too many cells (cost guard).
        """
        walls = gameState.getWalls()
        width, height = walls.width, walls.height

        open_cells = []
        for x in range(width):
            for y in range(height):
                if not walls[x][y]:
                    open_cells.append((x, y))

        if len(open_cells) > _BOTTLENECK_MAX_CELLS:
            return frozenset()

        bottlenecks = set()
        for cx, cy in open_cells:
            neighbors = []
            for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                nx, ny = cx + dx, cy + dy
                if 0 <= nx < width and 0 <= ny < height and not walls[nx][ny]:
                    neighbors.append((nx, ny))
            if len(neighbors) < 2:
                continue
            # BFS from neighbors[0] with (cx, cy) blocked.
            blocked = (cx, cy)
            src = neighbors[0]
            seen = {src}
            queue = deque([src])
            while queue:
                ux, uy = queue.popleft()
                for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                    vx, vy = ux + dx, uy + dy
                    if vx < 0 or vy < 0 or vx >= width or vy >= height:
                        continue
                    if walls[vx][vy]:
                        continue
                    if (vx, vy) == blocked:
                        continue
                    if (vx, vy) in seen:
                        continue
                    seen.add((vx, vy))
                    queue.append((vx, vy))
            # If any other neighbor is unreachable, (cx, cy) is a bottleneck.
            for n in neighbors[1:]:
                if n not in seen:
                    bottlenecks.add((cx, cy))
                    break
        return frozenset(bottlenecks)

    def _precomputeDeadEnds(self, gameState):
        """Cells with exactly one non-wall neighbor (true dead-ends), then
        extend backward along single-exit corridors as long as the corridor
        depth from the original tip is >= 3. Returns frozenset of all such
        cells (the tip and the corridor it sits in).

        Heuristic: the plan calls for "one non-wall neighbor and depth >= 3
        from nearest junction." We approximate by collecting any cell that
        sits on a length->=3 dead-end stub.
        """
        walls = gameState.getWalls()
        width, height = walls.width, walls.height

        def neighbors(p):
            x, y = p
            out = []
            for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                nx, ny = x + dx, y + dy
                if 0 <= nx < width and 0 <= ny < height and not walls[nx][ny]:
                    out.append((nx, ny))
            return out

        # Find tips (cells with exactly one open neighbor).
        tips = []
        for x in range(width):
            for y in range(height):
                if walls[x][y]:
                    continue
                if len(neighbors((x, y))) == 1:
                    tips.append((x, y))

        dead_cells = set()
        for tip in tips:
            chain = [tip]
            prev = None
            cur = tip
            # Walk inward through degree-2 corridor cells.
            while True:
                nbrs = [n for n in neighbors(cur) if n != prev]
                if len(nbrs) != 1:
                    break
                nxt = nbrs[0]
                # Stop when we reach a junction (degree >= 3 looking outward
                # from the corridor side). A junction is a cell with >= 3
                # open neighbors total.
                if len(neighbors(nxt)) >= 3:
                    break
                prev, cur = cur, nxt
                chain.append(cur)
            if len(chain) >= 3:
                dead_cells.update(chain)
        return frozenset(dead_cells)

    def _computeHomeFrontier(self, gameState):
        """List of cells on our side of the dividing column that are
        adjacent to the dividing column itself (the cells we patrol /
        retreat through)."""
        walls = gameState.getWalls()
        width, height = walls.width, walls.height
        # Dividing column convention from capture.py:
        #   isRed pos: pos.x < width / 2
        # so red side cells are x in [0, width//2 - 1]; the home-frontier
        # column for red is width//2 - 1, for blue it is width // 2.
        if self.red:
            frontier_x = width // 2 - 1
        else:
            frontier_x = width // 2
        if frontier_x < 0 or frontier_x >= width:
            return []
        cells = []
        for y in range(height):
            if not walls[frontier_x][y]:
                cells.append((frontier_x, y))
        return cells

# ===== zoo_reflex_tuned.py (ReflexTunedAgent + createTeam) =====
# zoo_reflex_tuned.py
# -------------------
# Tuned feature-reflex team agent. Seed for your_baseline1.py.
# Both teammates inherit CoreCaptureAgent; role (OFFENSE/DEFENSE) is assigned
# by TeamGlobalState.role[], defaulting to lower-index=OFFENSE,
# higher-index=DEFENSE.
#
# Decision rule: argmax over legal actions using role-appropriate weights.
# Tiebreak: deterministic preference order [North, East, South, West, Stop].




def createTeam(firstIndex, secondIndex, isRed,
               first='ReflexTunedAgent', second='ReflexTunedAgent',
               weights=None):
    """Construct the two teammate agents.

    Extra kwarg (M4b-2, pm8):
      weights — optional path to a JSON weights file (or a dict). When
                provided (passed via capture.py's `--redOpts weights=...`),
                the spec is loaded via zoo_core.load_weights_override and
                attached to each agent as `_weights_override`. The agent's
                `_get_weights()` then returns the override instead of the
                module-level seed weights. Used by evolve.py (M5/M6) to
                inject candidate genomes at runtime. Never raises — a bad
                `weights` path silently falls back to seed weights.
    """
    agents = [ReflexTunedAgent(firstIndex), ReflexTunedAgent(secondIndex)]
    if weights:
        try:
            override = load_weights_override(weights)
            # Only attach if non-empty — keeps the agent's fallback clean.
            if override.get('w_off') or override.get('w_def'):
                for a in agents:
                    a._weights_override = override
        except Exception:
            pass  # crash-proof: fall back to seed weights on any failure
    return agents


class ReflexTunedAgent(CoreCaptureAgent):
    """Tuned reflex agent with 20 features and role-based weight selection.

    If `self._weights_override` is attached (see createTeam `weights` kwarg),
    `_get_weights()` returns the override instead of the module-level seed.
    This is the runtime hook used by evolve.py to evaluate CEM candidates.
    """

    def _get_weights(self):
        """Return the weight dict appropriate for this agent's current role.

        Priority: runtime override > role-split seed weights.
        Override schema (from zoo_core.load_weights_override):
          {'w_off': {...}, 'w_def': {...} | None, 'params': {...}}
        If w_def is None (Phase 2a shared-W), DEFENSE role also uses w_off.
        """
        try:
            role = TEAM.role.get(self.index, 'OFFENSE')
        except Exception:
            role = 'OFFENSE'
        override = getattr(self, '_weights_override', None)
        if override:
            if role == 'DEFENSE' and override.get('w_def'):
                return override['w_def']
            if override.get('w_off'):
                return override['w_off']
            # override attached but empty — fall through to seed
        if role == 'DEFENSE':
            return SEED_WEIGHTS_DEFENSIVE
        return SEED_WEIGHTS_OFFENSIVE

    def _chooseActionImpl(self, gameState):
        """Argmax over legal actions using role-appropriate weights.

        Tiebreak: deterministic preference [North, East, South, West, Stop].
        """
        legal = gameState.getLegalActions(self.index)
        if not legal:
            return Directions.STOP

        weights = self._get_weights()

        best_score = float('-inf')
        best_action = None

        # Evaluate in preference order so first tie-preferred action wins.
        ordered = sorted(legal, key=lambda a: _ACTION_PREFERENCE.index(a)
                         if a in _ACTION_PREFERENCE else len(_ACTION_PREFERENCE))

        for action in ordered:
            try:
                score = evaluate(self, gameState, action, weights)
            except Exception:
                score = float('-inf')
            if score > best_score:
                best_score = score
                best_action = action

        if best_action is None or best_action not in legal:
            # Fallback: prefer non-STOP
            non_stop = [a for a in legal if a != Directions.STOP]
            return non_stop[0] if non_stop else Directions.STOP

        return best_action
