# zoo_reflex_O3.py  (auto-generated by experiments/make_hof_wrapper.py)
# ----------------------------------------------------------------------
# HOF (Hall-of-Fame) opponent wrapper: ReflexTunedAgent pinned to a
# previously-evolved champion's weights. Used as opponent in later
# evolve.py Order pools so new populations must out-perform this champion
# (AlphaZero-lite coevolution rotation).
#
# Provenance: /root/projects/coding-3/experiments/artifacts/phase2_A3_diverse_s1001_h1test/final_weights.py (W_OFF: 20 keys, W_DEF: 20 keys)
# Number of W_OFF entries: 20
# Number of W_DEF entries: 20
#
# Never submitted; minicontest-only training opponent.

from __future__ import annotations

from pathlib import Path

from zoo_reflex_tuned import ReflexTunedAgent

_REPO_ROOT = Path(__file__).resolve().parent.parent

# Try multiple candidate paths for robustness across Mac/server layouts.
_WEIGHT_PATHS = [
    _REPO_ROOT / 'experiments/artifacts/phase2_A3_diverse_s1001_h1test/final_weights.py',
    Path('/root/projects/coding-3/experiments/artifacts/phase2_A3_diverse_s1001_h1test/final_weights.py'),
]


def _load_override():
    """Load W_OFF / W_DEF from the weights archive. Never raises."""
    import importlib.util
    import sys as _sys
    for path in _WEIGHT_PATHS:
        if not path.exists():
            continue
        try:
            spec = importlib.util.spec_from_file_location("_hof_weights", str(path))
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            w_off = dict(getattr(mod, "W_OFF", {}))
            w_def_raw = dict(getattr(mod, "W_DEF", {}))
            w_def = w_def_raw or None
            return {
                "w_off": w_off,
                "w_def": w_def,
                "params": dict(getattr(mod, "PARAMS", {})),
            }
        except Exception as exc:
            try:
                print(f"[zoo_reflex_O3] warn: load failed from {path}: {exc}",
                      file=_sys.stderr)
            except Exception:
                pass
            continue
    try:
        print(
            f"[zoo_reflex_O3] warn: no weights file found; falling back to seed weights",
            file=_sys.stderr,
        )
    except Exception:
        pass
    return {"w_off": {}, "w_def": None, "params": {}}


_OVERRIDE = _load_override()


class ReflexO3Agent(ReflexTunedAgent):
    """ReflexTunedAgent with ReflexO3Agent evolved weights pinned at construction."""

    def __init__(self, index, timeForComputing=0.1):
        super().__init__(index, timeForComputing=timeForComputing)
        if _OVERRIDE.get("w_off"):
            self._weights_override = _OVERRIDE


def createTeam(firstIndex, secondIndex, isRed,
               first="ReflexO3Agent", second="ReflexO3Agent"):
    return [ReflexO3Agent(firstIndex), ReflexO3Agent(secondIndex)]
